export const linkList: any = [
    {
        id: 1,
        displayName: 'Eorzea Overview',
        iconName: 'eorzeaMap',
        feature: true,
        href: '/eorzeaOverview'
    },
    {
        id: 2,
        displayName: 'Timed Mining & Botany',
        iconName: 'gathering',
        feature: true,
        href: '/timedMiningBotany',
    },
    {
        id: 3,
        displayName: 'Timed Fishing',
        iconName: 'fishing',
        feature: true,
        href: '/timedFishing',
    },
    {
        id: 4,
        displayName: 'Sightseeing Vistas',
        iconName: 'sightseeing',
        feature: false,
        href: '/sightseeingVistas',
    },
    {
        id: 5,
        displayName: 'Aether Currents',
        iconName: 'aethercurrents',
        feature: false,
        href: '/aetherCurrents',
    },
    {
        id: 6,
        displayName: 'Blue Mage Abilities',
        iconName: 'bluemage',
        feature: false,
        href: '/blueMageAbilities',
    },
    {
        id: 7,
        displayName: 'Weather Patterns',
        iconName: 'weather',
        feature: false,
        href: '/weatherPatterns',
    },
    {
        id: 10,
        displayName: 'FFXIV Radar News',
        iconName: 'news',
        feature: false,
        href: '/news',
    },
    {
        id: 11,
        displayName: 'About Us',
        iconName: 'about',
        feature: false,
        href: '/aboutUs',
    },
    {
        id: 12,
        displayName: 'Privacy Policy',
        iconName: 'privatepolicy',
        feature: false,
        href: '/privatePolicy',
    },
]